steps:
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'twittrstreamer_function', '--trigger-topic=start-streamer', 
    '--runtime=python38', '--entry-point=triggering_streamer',
    '--source=https://source.developers.google.com/projects/twitternlp-314312/repos/github_juanjtov_twitter_analysis_colombia_dashboard/moveable-aliases/main/paths/TWEETS_STREAMER']
    